version: '3.8'

networks:
  default:

services:
   db:
     image: mysql:5.7
     container_name: conference_security
     ports:
       - 3306:3306
     volumes:
       - "./.data/db:/var/lib/mysql"
     environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: conference_security
       
    